pidfile = /opt/src/git/gonggo/pid/gonggo.pid
logpath = /opt/src/git/gonggo/log
sslcert = /opt/src/git/gonggo/ssl/server.pem
port = 8877s
threads = 10
gonggo = gonggo
heartbeatperiod = 30 #in seconds
heartbeattimeout = 1.15 #multiple of heartbeatperiod
dbpath = /opt/src/git/gonggo/db
respondretainoverdue = 900 #in seconds
respondretainperiod = 5 #in seconds
respondquerysize = 5
