#ifndef _GONGGO_STATUS_H_
#define _GONGGO_STATUS_H_

enum ServiceStatus {
    SERVICE_STATUS_REQUEST_ACKNOWLEDGED = 0,
    SERVICE_STATUS_REQUEST_ANSWERED = 1,
    SERVICE_STATUS_INTERNAL_ERROR = 2,
    SERVICE_STATUS_INVALID_PAYLOAD = 3,
    SERVICE_STATUS_RID_OVERLENGTH = 4,
    SERVICE_STATUS_PATH_OVERLENGTH = 5,
    SERVICE_STATUS_TASK_EMPTY = 6,
    SERVICE_STATUS_TASK_OVERLENGTH = 7,
    SERVICE_STATUS_PROXY_NOT_AVAILABLE = 8,
    SERVICE_STATUS_PROXY_NOT_ACCESSIBLE = 9,
    SERVICE_STATUS_PROXY_BUSY = 10,
    SERVICE_STATUS_PROXY_CHANNEL_OPEN_FAILED = 11,
    SERVICE_STATUS_PROXY_CHANNEL_ACCESS_FAILED = 12,
    SERVICE_STATUS_PROXY_CHANNEL_BUSY = 13,
    SERVICE_STATUS_PROXY_CHANNEL_DIED = 14,
    SERVICE_STATUS_PROXY_CHANNEL_INVALID_TASK = 15,
    SERVICE_STATUS_PROXY_CHANNEL_INVALID_PAYLOAD = 16,
    SERVICE_STATUS_PROXY_CHANNEL_INVALID_STATE = 17
};

extern const char* service_status(enum ServiceStatus status);

#endif //_GONGGO_STATUS_H_
